apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mkeaws
spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        image: devchatdemo:latest
        imagePullPolicy: Always
        name: mkewas
        ports:
        - containerPort: 80
